<?php
	class ExaminfoController extends CControl{
		public function __construct() {
			set_time_limit(0);
	        parent::__construct();
	        $this->haspower = Ebh::app()->room->checkRoomControl();
			//Ebh::app()->room->checkteacher();
	       
	    }
		public function index(){
			$roominfo = EBH::app()->room->getcurroom();
			$classesModel = $this->model('classes');
			$examlist = $classesModel->getschoolexams($roominfo['crid']);
			$examlist = $this->parsegrade($examlist);
			// var_dump($examlist);die();
			$this->export($examlist);
		}
		public function export($examlist){
			$examlist = array_values($examlist);
			$count = count($examlist);
			$objExcel = EBH::app()->lib('PHPExcel');
			$objWriter = new PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式  
			$objProps = $objExcel->getProperties();
			//$objProps->setCreator("Zeal Li");  
			//$objProps->setLastModifiedBy("Zeal Li");  
			//$objProps->setTitle("Office XLS Test Document");  
			//$objProps->setSubject("Office XLS Test Document, Demo");  
			//$objProps->setDescription("Test document, generated by PHPExcel.");  
			//$objProps->setKeywords("office excel PHPExcel");  
			$objExcel->setActiveSheetIndex(0);
			$objActSheet = $objExcel->getActiveSheet();
			//设置当前活动sheet的名称
			$objActSheet->setCellValue('A1', '班级或年级');  
			$objActSheet->setCellValue('B1', '学科');  
			$objActSheet->setCellValue('C1', '作业名称');   
			$objActSheet->setCellValue('D1', '上传人');  
			$objActSheet->setCellValue('E1', '学生人数');  
			$objActSheet->setCellValue('F1', '完成人数');  
			$objActSheet->setCellValue('G1', '未完成人数');    
			$objActSheet->setCellValue('H1', '已批改数');    
			$objActSheet->setCellValue('I1', '未批改数');    
			$objActSheet->setCellValue('J1', '发布时间');     
			$objActSheet->setTitle('作业导出');  
			foreach ($examlist as $key => $exam) {
				$i = $key+2;
				$tname = empty($exam['realname'])?$exam['username']:$exam['realname'];
				$foldername = empty($exam['foldername'])?'':$exam['foldername'];
				$objActSheet->setCellValue('A'.$i, ' '.$exam['classname']);  
				$objActSheet->setCellValue('B'.$i, ' '.$foldername);  
				$objActSheet->setCellValue('C'.$i, ' '.$exam['title']);
				$objActSheet->setCellValue('D'.$i, $tname); 
				$objActSheet->setCellValue('E'.$i, $exam['stunum']); 
				$objActSheet->setCellValue('F'.$i, $exam['tj']);
				$objActSheet->setCellValue('G'.$i, $exam['stunum']-$exam['tj']);
				$objActSheet->setCellValue('H'.$i, $exam['pg']);
				$objActSheet->setCellValue('I'.$i, $exam['tj']-$exam['pg']);
				$objActSheet->setCellValue('j'.$i, date('Y-m-d H:i',$exam['dateline']));
			}
			//设置宽度 
			$objActSheet->getColumnDimension('A')->setWidth(30);   
			$objActSheet->getColumnDimension('B')->setWidth(20);  
			$objActSheet->getColumnDimension('C')->setWidth(30);  
			$objActSheet->getColumnDimension('D')->setWidth(15);  
			$objActSheet->getColumnDimension('E')->setWidth(15);  
			$objActSheet->getColumnDimension('F')->setWidth(15);  
			$objActSheet->getColumnDimension('G')->setWidth(15);  
			$objActSheet->getColumnDimension('H')->setWidth(15);  
			$objActSheet->getColumnDimension('I')->setAutoSize(true);  
			$objActSheet->getColumnDimension('J')->setAutoSize(true);  
			$cols = array('A','B','C','D','E','F','G','H','I','J');
			for($j=1;$j<=$count+1;$j++){
				foreach ($cols as $col) {
				  	
					
					$objStyleA5 = $objActSheet->getStyle($col.$j);  
					$objFontA5 = $objStyleA5->getFont();    
					if($j==1){
						$objFontA5->setBold(true);
						// $objFontA5->getColor()->setARGB('FF999999');    
					}else{
						$objFontA5->setBold(false);    
					}
					//设置对齐方式    
					  
					$objAlignA5 = $objStyleA5->getAlignment();    
					if(($col=='A')&&($j!=1)){
						$objAlignA5->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT); //水平  
					}else{
						$objAlignA5->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER); //水平  
					}  
					 
					  
					$objAlignA5->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);  //垂直  
				  
				}
			}


			$outputFileName = '作业统计'. ".xls";
			header("Content-Type: application/force-download");
			header("Content-Type: application/octet-stream");
			header("Content-Type: application/download");
			header('Content-Disposition:attachment;filename="' . $outputFileName . '"');  //到文件
			// header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
			header("Content-Transfer-Encoding: binary");
			header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
			header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
			header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
			header("Pragma: no-cache");
			$objWriter->save('php://output');
		}	  
		public function parsegrade($newinfo){

			$roominfo = Ebh::app()->room->getcurroom();
			$crid = $roominfo['crid'];
			$fnewinfo = array();
			$stunum = array();
			foreach ($newinfo as  $nv) {
				$fk = md5($nv['crid'].'-'.$nv['district'].'-'.$nv['title'].'-'.$nv['dateline']);
				$skey = md5($nv['crid'].$nv['district'].$nv['grade']);
				if($nv['grade']>0){
					
					if(array_key_exists($fk, $fnewinfo)){

						if(!array_key_exists($skey, $stunum)){
							$stunum[$skey] = $this->model('classes')->getstunum($nv['crid'],$nv['grade'],$nv['district']);
							$fnewinfo[$fk]['stunum'] = $stunum[$skey];
						}else{
							$fnewinfo[$fk]['stunum'] = $stunum[$skey];
						}
						
						// echo $fnewinfo[$fk]['stunum'];
						$fnewinfo[$fk]['pg']+=$nv['pg'];
						// $fnewinfo[$fk]['tj']+=$nv['tj'];
					}else{
						$gradekey = $nv['grade'];
						$nv['classname'] = $this->getGradeName($gradekey,$nv['district'],$roominfo['crid']);
						$fnewinfo[$fk] = $nv;
						if(!array_key_exists($skey, $stunum)){
							$stunum[$skey] = $this->model('classes')->getstunum($nv['crid'],$nv['grade'],$nv['district']);
							$fnewinfo[$fk]['stunum'] = $stunum[$skey];
						}else{
							$fnewinfo[$fk]['stunum'] = $stunum[$skey];
						}
					}
					
				}else{
					$fnewinfo[$fk] = $nv;
				}
				
			}
			return $fnewinfo;
	}

	public function getGradeName($gradekey,$district,$crid){
		$gradename = '';
		$gradeReflection = array(
				'1'=>'一年级','2'=>'二年级','3'=>'三年级','4'=>'四年级','5'=>'五年级',
				'6'=>'六年级','7'=>'初一','8'=>'初二','9'=>'初三','10'=>'高一',
				'11'=>'高二','12'=>'高三'
				);
		if(array_key_exists($gradekey, $gradeReflection)){
			$gradename = $gradeReflection[$gradekey];
		}else{
			$gradename = '自定义年级'.$gradekey;
		}
		if($crid==10420){
			$districtname = array('','(下沙校区)','(吴山校区)');
		}else{
			$districtname = array('','','(校区二)');
		}
		$gradename.=$districtname[$district];
		return $gradename;
	}


}