<?php
	class CoursewareinfoController extends CControl{
		public function __construct() {
	        parent::__construct();
	        set_time_limit(0);
	        Ebh::app()->room->checkteacher();
	       
	    }
		public function index(){
			$roominfo = EBH::app()->room->getcurroom();
			$coursewareModel = $this->model('courseware');
			// $roominfo['crid'] = 10192;
			$clist = $coursewareModel->getSchoolCourseware($roominfo['crid']);
			$this->export($clist);
		}
		public function export($clist){
			$roominfo = EBH::app()->room->getcurroom();
			$count = count($clist);
			$objExcel = EBH::app()->lib('PHPExcel');
			$objWriter = new PHPExcel_Writer_Excel5($objExcel);   // 用于其他版本格式  
			$objProps = $objExcel->getProperties();
			//$objProps->setCreator("Zeal Li");  
			//$objProps->setLastModifiedBy("Zeal Li");  
			//$objProps->setTitle("Office XLS Test Document");  
			//$objProps->setSubject("Office XLS Test Document, Demo");  
			//$objProps->setDescription("Test document, generated by PHPExcel.");  
			//$objProps->setKeywords("office excel PHPExcel");  
			$objExcel->setActiveSheetIndex(0);
			$objActSheet = $objExcel->getActiveSheet();
			//设置当前活动sheet的名称
			$objActSheet->setCellValue('A1', '班级或年级');  
			$objActSheet->setCellValue('B1', '学科');  
			$objActSheet->setCellValue('C1', '视频名称');   
			$objActSheet->setCellValue('D1', '制作人');  
			$objActSheet->setCellValue('E1', '点击量');    
			$objActSheet->setCellValue('F1', '发布时间');     
			$objActSheet->setTitle('课件统计'); 
			foreach ($clist as $key => $courseware) {
				$i = $key+2;
				$tname = empty($courseware['realname'])?$courseware['username']:$courseware['realname'];
				if(empty($courseware['classname'])){
					if($courseware['grade']>0){
						$gradename = $this->getGradeName($courseware['grade'],0,$roominfo['crid']);
					}else{
						$gradename = '学校-'.$roominfo['crname'];
					}
				}else{
					$gradename = $courseware['classname'];
				}
				
				$foldername = empty($courseware['foldername'])?'':$courseware['foldername'];
				$objActSheet->setCellValue('A'.$i, ' '.$gradename);  
				$objActSheet->setCellValue('B'.$i, ' '.$foldername);  
				$objActSheet->setCellValue('C'.$i, ' '.$courseware['title']);
				$objActSheet->setCellValue('D'.$i, $tname); 
				$objActSheet->setCellValue('E'.$i, $courseware['viewnum']);
				$objActSheet->setCellValue('F'.$i, date('Y-m-d H:i',$courseware['dateline']));
			}
			//设置宽度 
			$objActSheet->getColumnDimension('A')->setWidth(15);   
			$objActSheet->getColumnDimension('B')->setWidth(20);  
			$objActSheet->getColumnDimension('C')->setWidth(90);  
			$objActSheet->getColumnDimension('D')->setWidth(15);  
			$objActSheet->getColumnDimension('E')->setWidth(15);  
			$objActSheet->getColumnDimension('F')->setWidth(20);  
			$cols = array('A','B','C','D','E','F');
			for($j=1;$j<=$count+1;$j++){
				foreach ($cols as $col) {
				  	
					
					$objStyleA5 = $objActSheet->getStyle($col.$j);  
					$objFontA5 = $objStyleA5->getFont();    
					if($j==1){
						$objFontA5->setBold(true);
						// $objFontA5->getColor()->setARGB('FF999999');    
					}else{
						$objFontA5->setBold(false);    
					}
					//设置对齐方式    
					  
					$objAlignA5 = $objStyleA5->getAlignment();    
					if(($col=='A')&&($j!=1)){
						$objAlignA5->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_LEFT); //水平  
					}else{
						$objAlignA5->setHorizontal(PHPExcel_Style_Alignment::HORIZONTAL_CENTER); //水平  
					}  
					 
					  
					$objAlignA5->setVertical(PHPExcel_Style_Alignment::VERTICAL_CENTER);  //垂直  
				  
				}
			}


			$outputFileName = '课件统计' . ".xls";
			header("Content-Type: application/force-download");
			header("Content-Type: application/octet-stream");
			header("Content-Type: application/download");
			header('Content-Disposition:attachment;filename="' . $outputFileName . '"');  //到文件
			// header('Content-Disposition:inline;filename="'.$outputFileName.'"');  //到浏览器
			header("Content-Transfer-Encoding: binary");
			header("Expires: Mon, 26 Jul 1997 05:00:00 GMT");
			header("Last-Modified: " . gmdate("D, d M Y H:i:s") . " GMT");
			header("Cache-Control: must-revalidate, post-check=0, pre-check=0");
			header("Pragma: no-cache");
			$objWriter->save('php://output');
		}	  
		

	public function getGradeName($gradekey,$district=0,$crid){
		$gradename = '';
		$gradeReflection = array(
				'0'=>'学前教育','1'=>'一年级','2'=>'二年级','3'=>'三年级','4'=>'四年级','5'=>'五年级',
				'6'=>'六年级','7'=>'初一','8'=>'初二','9'=>'初三','10'=>'高一',
				'11'=>'高二','12'=>'高三'
				);
		if(array_key_exists($gradekey, $gradeReflection)){
			$gradename = $gradeReflection[$gradekey];
		}else{
			$gradename = '自定义年级'.$gradekey;
		}
		if($crid==10420){
			$districtname = array('','(下沙校区)','(吴山校区)');
		}else{
			$districtname = array('','','(校区二)');
		}
		$gradename.=$districtname[$district];
		return $gradename;
	}
}